config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :rooms do
    resources :bookings
  end

  resources :hotels do
    resources :rooms, only: [:index, :show]
  end

  resources :rooms, only: [:index, :show]
  resources :bookings, only: [:index, :show, :edit, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :starts_at, presence: true
  validates :ends_at, presence: true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  has_many :rooms, dependent: :destroy
  has_many :bookings, through: :rooms, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  validates :capacity, presence: true
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :price_per_night, presence: true
  validates :capacity, numericality: { greater_than: 0 }
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def edit
    @booking = Booking.new
  end

  def create
    @room = room.find(params[:room_id])
    @booking = Booking.new(booking_params)
    if @booking.save!
    redirect_to root_path
    else
    render :new
    end
  end

  private
    def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :room_id, :user_id)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @hotel = Hotel.all
  end

  def show
    @hotel = Hotel.new()
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
  end
end


private
def room_params
  params.require(:room).permit(:name, :address, :hotel_id)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/hotels/index.html.erb
<h1>Hotels#index</h1>
<p>Find me in app/views/hotels/index.html.erb</p>

app/views/hotels/show.html.erb
<h1>Hotels#show</h1>
<p>Find me in app/views/hotels/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CertifHotel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
        <%= render "shared/flashes" %>

    <div class= "container">
       <%= yield %>
    </div>


    </body>
</html>

app/views/pages/home.html.erb
<h1>Location de chambres d'hotels</h1>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Service de location de chambre d'hotel pour particulier</strong>!</h1>
    <p>Faites vos réservations en toutes tranquilités sur notre site.</p>
    <%= link_to "Voir nos chambres", rooms_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/delete.html.erb
<h1>Rooms#delete</h1>
<p>Find me in app/views/rooms/delete.html.erb</p>

app/views/rooms/edit.html.erb
<h1>Liste de nos chambres</h1>

app/views/rooms/index.html.erb
<h1>Liste de nos chambres</h1>
<%= render "shared/room_card" %>

app/views/rooms/new.html.erb
<h1>Rooms#new</h1>
<p>Find me in app/views/rooms/new.html.erb</p>

app/views/rooms/show.html.erb
<div class="room_details">
    <h1>Détails de la chambre <%= @room.id %></h1>
    <div class="card-trip">
        <img src="<%= @room.photo %>"/>
        <div class="card-trip-infos">
            <div>
            <h2>Chambre <%= @room.id %></h2>
            <p>la capacité de cette chambre est de <%= @room.capacity %> occupant(s)</p>
            </div>
            <h2 class="card-trip-pricing"><%= @room.price_per_night %> €</h2>
        </div>
    </div>
    <hr>

    <div class="room-info">
        <div class="room-details">
            <p>
                Lorem ipsum dolor sit amet. Ut iusto quisquam eos recusandae beatae qui fuga alias ea nihil deserunt id dolorem quisquam eum sunt voluptatem non alias omnis. Ab odit provident ea dolorem earum et consequatur quia eum voluptatem iusto non fugit unde nam velit autem. Ut atque ipsam 33 eligendi adipisci cum earum dolore qui consequatur alias aut voluptas suscipit cum totam aliquid hic excepturi sint. Sed molestiae natus in maxime consequuntur et itaque dicta ea dicta repellendus aut optio dolores non voluptas voluptas.
            </p>
            <p>
                Non rerum quod est reprehenderit animi et quaerat recusandae aut aspernatur molestias ea internos modi in dolorem molestias ea internos delectus. Aut rerum explicabo eum veniam repellat vel ipsa placeat aut accusantium facilis qui placeat deleniti.
            </p>
        </div>

        <div class="room-reza">
            <%= render "shared/reza" %>
        </div>
    </div>


</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_reza.html.erb
<div class="reza-box">
    <div>
        <p><strong><%= @room.price_per_night %></strong> €</p>
    </div>
          <%= simple_form_for(@booking) do |f| %>
            <div class="reza-start">
                <%= f.input :starts_at, class: "dated" %>
              </div>
            <hr>
            <div class="reza-end"></div>
        <% end %>

    </div>
    <div class="reza-capacity"></div>

</div>

app/views/shared/_room_card.html.erb
<div class="card_container">
    <% @rooms.each do |room| %>
        <div class="card-elements">
            <a href= "<%= room_path(room.id) %>" >
                <div class="card-img">
                    <%= image_tag(room.photo, size: "300x300", alt: "Edit Entry", class: "menu_icon") %>
                </div>
                <div class="card-infos">
                    <h2>Chambre N° <%= room.id %></h2>
                    <p><strong><%= room.price_per_night %> €</strong> par nuits <br>
                    Capacité de la chambre : <%= room.capacity %>
                    </p>
                </div>
            </a>
        </div>
    <% end %>
</div>